insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (201,21,'freshman',true, 'Gider', 'Hakan', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (202,22,'sophomore',false, 'Kagit', 'Huseyin', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (203,23,'sophomore',false, 'Yasar', 'Cubuklu', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (204,24,'sophomore',true, 'Ergun', 'Gudullu', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (205,25,'senior',false, 'Turgut', 'Ankarali', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (206,21,'junior',true, 'Demirtas', 'Mehmet', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (207,22,'freshman',false, 'Yasemin', 'Ankarali', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (208,23,'freshman',false, 'Ucar', 'Tahir', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (209,24,'sophomore',false, 'Akbayram', 'Edip', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (210,25,'junior',false, 'Oge', 'Kamil', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (211,31,'senior',false, 'Eroglu', 'Musa', CURRENT_DATE());
