insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (101,21,'freshman',true, 'Gider', 'Hakan', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (102,22,'sophomore',false, 'Kagit', 'Huseyin', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (103,23,'sophomore',false, 'Yasar', 'Cubuklu', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (104,24,'sophomore',true, 'Ergun', 'Gudullu', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (105,25,'senior',false, 'Turgut', 'Ankarali', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (106,21,'junior',true, 'Demirtas', 'Mehmet', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (107,22,'freshman',false, 'Yasemin', 'Ankarali', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (108,23,'freshman',false, 'Ucar', 'Tahir', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (109,24,'sophomore',false, 'Akbayram', 'Edip', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (110,25,'junior',false, 'Oge', 'Kamil', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (111,31,'senior',false, 'Eroglu', 'Musa', CURRENT_DATE());
insert into STUDENT(STUDENT_ID, AGE, GRADE, IS_FULL_TIME, LASTNAME, NAME, UPDATED_ON)
VALUES (112,32,'senior',false, 'Serif', 'Mahsuni', CURRENT_DATE());
